---
title: "Outcome of Basketball"
author: "Muxing Wang"
date: '2022-06-08'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

suppose $y_1 \sim Pois(\lambda_1), y_2\sim Pois(\lambda_2)$

$$
P(y_1 = y_2) = \sum_{k=0}^{\infty} P(y_1=k, y_2 = k) \overset{\mathrm{indep}}{=}
 \sum_{k=0}^{\infty} P(y_1 = k)P(y_2 = k) = \sum_{k=0}^{\infty} 
\frac{e^{-\lambda_1}\lambda_1^k}{k!}\frac{e^{-\lambda_2}\lambda_2^k}{k!} = 
\sum_{k=0}^{\infty}\frac{e^{-\lambda_1-\lambda_2}(\lambda_1\lambda_2)^k}{(k!)^2}
$$

I found Skellam distribution can describe such events, therefore I just adopted it.

```{r}
library(INLA)
library(dplyr)
library(magrittr)
library(locfit)
library(extraDistr)
K=120
lambda1 = 4
lambda2 = 6
prob2 = 0
for(k in 0:K){
    prob2 = prob2+ (1-sum(exp(-lambda1)*lambda1**(0:k)/factorial(0:k)))*exp(-lambda2)*lambda2**k/factorial(k)
}
prob = 0
for(i in 1:100){
  prob = prob + dskellam(i,4,6,log=FALSE)
}
denominator = 1- exp(-lambda1-lambda2)* sum((lambda1*lambda2)**(0:K)/factorial((0:K))**2)
deno.skellam = 1 - dskellam(0,4,6,log=FALSE)
print(prob - prob2)
print(deno.skellam - denominator)
```

## Helper functions

```{r}
## team1 wins
winning.prob = function(lambda1,lambda2){
  sum(dskellam(1:100,lambda1,lambda2,log=FALSE))/(1 - dskellam(0,lambda1,lambda2,log=FALSE))
}
# ranked probability score
rps<- function(obs,pred, R){
  res = 0
  for (i in 1:(R-1)){
    subres = 0
    for(j in 1:i){
      subres = subres + (pred[j] - obs[j])
    }
    res = res + subres**2
  }
  res* 1/ (R-1)
}
rps(c(1,0,0),c(0.8,0.2,0),3)
```

## Reading data

```{r}
#path = 'newdat/games2019_v1.csv'
path = 'newdat/games_extended.csv'
games.total = read.csv(path)

## change type to date
games.total %<>%
  mutate(GAME_DATE_EST= as.Date(GAME_DATE_EST, format= "%m/%d/%Y"))



#[start ------training-------)--[split-------testing-------end]
dates = unique(games.total$GAME_DATE_EST)
                      ##  end           season
#split = "2021-05-22" ##  2021-07-20  2020-2021    2020.csv
#split = "2020-08-17"  ## 2020-10-11  2019-2020    2019.csv
#split = "2019-04-13"  ## 2019-06-13  2018-2019    2018.csv
#split = "2018-04-14"  ## 2018-06-08  2017-2018    2017.csv
#split = "2017-04-15"  ## 2017-06-12  2016-2017    2016.csv
#split = "2016-04-13"  ## 2016-06-19  2015-2016    2015.csv
#split = "2015-04-15"  ## 2015-06-16  2014-2015    2014.csv 
#split = "2014-04-19"  ## 2014-06-15  2013-2014    2013.csv
#split = "2013-04-20"  ## 2013-06-20  2012-2013    2012.csv
#split = "2012-04-28"  ## 2012-06-21  2011-2012    2011.csv
#split = "2011-04-16"  ## 2011-06-12  2010-2011    2010.csv
#split = "2010-04-17"  ## 2010-06-17  2009-2010    2009.csv
#split = "2009-04-18"  ## 2009-06-14  2008-2009    2008.csv
#split = "2008-04-19"  ## 2008-06-17  2007-2008    2007.csv
#split = "2007-04-21"  ## 2007-06-14  2006-2007    2006.csv
#split = "2006-04-22"  ## 2006-06-20  2005-2006    2005.csv
#split = "2005-04-23"  ## 2005-06-23  2004-2005    2004.csv

split = "2018-04-14" # 

start.date = dates[length(dates)]
start.date = "2019-06-13"
end.date = "2020-10-11"
games.sub = games.total[games.total$GAME_DATE_EST<=end.date,] ## the dataset used for training and testing
games.sub = games.sub[games.sub$GAME_DATE_EST>start.date,]

games.sub = games.total[(games.total$SEASON == 2017)|(games.total$SEASON == 2016)|(games.total$SEASON == 2015)|(games.total$SEASON == 2014)|(games.total$SEASON == 2013)|(games.total$SEASON == 2012),]
games.true = games.sub
games.sub$PTS_home[games.sub$GAME_DATE_EST>=split] = NA  ## for prediction
games.sub$PTS_away[games.sub$GAME_DATE_EST>=split] = NA

games.sub$HOME_TEAM_WINS[games.sub$GAME_DATE_EST>=split] = NA




games.sub$PTS_home_cur_season[games.sub$PTS_home_cur_season == 0] <- NA #1
games.sub$PTS_LOST_home_cur_season[games.sub$PTS_LOST_home_cur_season == 0] <- NA #1
games.sub$FG_PCT_home_cur_season[games.sub$FG_PCT_home_cur_season == 0] <- NA #2
games.sub$FT_PCT_home_cur_season[games.sub$FT_PCT_home_cur_season == 0] <- NA #3
games.sub$FG3_PCT_home_cur_season[games.sub$FG3_PCT_home_cur_season == 0] <- NA #4
games.sub$AST_home_cur_season[games.sub$AST_home_cur_season == 0] <- NA #5
games.sub$REB_home_cur_season[games.sub$REB_home_cur_season == 0] <- NA #6

games.sub$PTS_away_cur_season[games.sub$PTS_away_cur_season == 0] <- NA #7
games.sub$PTS_LOST_away_cur_season[games.sub$PTS_LOST_away_cur_season == 0] <- NA #7
games.sub$FG_PCT_away_cur_season[games.sub$FG_PCT_away_cur_season == 0] <- NA #8
games.sub$FT_PCT_away_cur_season[games.sub$FT_PCT_away_cur_season == 0] <- NA #9
games.sub$FG3_PCT_away_cur_season[games.sub$FG3_PCT_away_cur_season == 0] <- NA #10
games.sub$AST_away_cur_season[games.sub$AST_away_cur_season == 0] <- NA #11
games.sub$REB_away_cur_season[games.sub$REB_away_cur_season == 0] <- NA #12
print(path)
```

## Pre-processing

```{r}


G = nrow(games.sub)
y1 = games.sub$PTS_home
y2 = games.sub$PTS_away
y = c(y1,y2)

y1.binary = games.sub$HOME_TEAM_WINS
y.binary = c(y1.binary, 1-y1.binary)

a1 = as.character(games.sub$NAME_HOME)
a2 = as.character(games.sub$NAME_AWAY)
a = as.factor(c(a1,a2))
d = as.factor(c(a2,a1))
h1 = rep(1, G)
h2 = rep(0, G)
h = c(h1,h2)

PTS_cur_season = c(games.sub$PTS_home_cur_season, games.sub$PTS_away_cur_season)
PTS_cur_season_oppo = c(games.sub$PTS_away_cur_season,games.sub$PTS_home_cur_season)

PTS_LOST_cur_season = c(games.sub$PTS_LOST_home_cur_season, games.sub$PTS_LOST_away_cur_season)
PTS_LOST_cur_season_oppo = c(games.sub$PTS_LOST_away_cur_season,games.sub$PTS_LOST_home_cur_season)

FG_PCT_cur_season = c(games.sub$FG_PCT_home_cur_season, games.sub$FG_PCT_away_cur_season)
FG_PCT_cur_season_oppo = c(games.sub$FG_PCT_away_cur_season, games.sub$FG_PCT_home_cur_season)

FT_PCT_cur_season = c(games.sub$FT_PCT_home_cur_season, games.sub$FT_PCT_away_cur_season)
FT_PCT_cur_season_oppo = c(games.sub$FT_PCT_away_cur_season,games.sub$FT_PCT_home_cur_season)

FG3_PCT_cur_season = c(games.sub$FG3_PCT_home_cur_season, games.sub$FG3_PCT_away_cur_season)
FG3_PCT_cur_season_oppo = c(games.sub$FG3_PCT_away_cur_season,games.sub$FG3_PCT_home_cur_season)

AST_cur_season = c(games.sub$AST_home_cur_season, games.sub$AST_away_cur_season)
AST_cur_season_oppo = c(games.sub$AST_away_cur_season,games.sub$AST_home_cur_season)
REB_cur_season = c(games.sub$REB_home_cur_season, games.sub$REB_away_cur_season)
REB_cur_season_oppo = c(games.sub$REB_away_cur_season,games.sub$REB_home_cur_season)
WINRATE_cur_season = c(games.sub$WINRATE_home_cur_season, games.sub$WINRATE_away_cur_season)
WINRATE_cur_season_oppo = c(games.sub$WINRATE_away_cur_season,games.sub$WINRATE_home_cur_season)

ROUND = c(games.sub$round_number_home, games.sub$round_number_away)

season = c(games.sub$SEASON, games.sub$SEASON)

data = data.frame(y,y.binary,a,d,h,PTS_cur_season,FG_PCT_cur_season,FT_PCT_cur_season,FG3_PCT_cur_season,AST_cur_season,REB_cur_season,WINRATE_cur_season,
                  PTS_cur_season_oppo,FG_PCT_cur_season_oppo,FT_PCT_cur_season_oppo,FG3_PCT_cur_season_oppo,AST_cur_season_oppo,REB_cur_season_oppo,WINRATE_cur_season_oppo,ROUND,PTS_LOST_cur_season,PTS_LOST_cur_season_oppo, season)
```

### covariance matrix

```{r}
Z <- model.matrix (~ 0 + a + d, data = data)
Q.beta <- Diagonal(59, 0.001)
```

## Poisson Regression Modelling

```{r}
print(Sys.time())
#+PTS_cur_season_oppo+FG_PCT_cur_season_oppo+FT_PCT_cur_season_oppo+FG3_PCT_cur_season_oppo+AST_cur_season_oppo+REB_cur_season_oppo+WINRATE_cur_season_oppo + PTS_LOST_cur_season+PTS_LOST_cur_season_oppo
basketball.inla = inla(y~1+a+d+h+PTS_cur_season+FG_PCT_cur_season+FT_PCT_cur_season+FG3_PCT_cur_season+AST_cur_season+REB_cur_season+WINRATE_cur_season+ PTS_LOST_cur_season
                       +f(season, model = "ar1c", args.ar1c = list(Z = Z, Q.beta = Q.beta)), data = data, family = "poisson",control.compute=list(config = TRUE,cpo = TRUE,dic = TRUE),control.predictor = list(compute = TRUE),verbose = TRUE)

samp.r <- inla.posterior.sample(1000, basketball.inla)

predictors.r=inla.posterior.sample.eval(function(...) {Predictor}, samp.r)

to.be.predicted = which(is.na(data$y))

number.matches = length(to.be.predicted)/2

predictors.test = predictors.r[to.be.predicted,]

lambda.test = exp(predictors.test)

winning.prob.matrix = matrix(rep(0,number.matches*1000),nrow = number.matches,ncol = 1000)

for(i in 1:number.matches){
  for( j in 1:1000){
    winning.prob.matrix[i,j] = winning.prob(lambda.test[i,j],lambda.test[i+number.matches,j])
  }
}

obs.win = games.true$HOME_TEAM_WINS[to.be.predicted[1:number.matches]]

true.score =c( games.true[to.be.predicted[1:number.matches],]$PTS_home,games.true[to.be.predicted[1:number.matches],]$PTS_away)

pred.win.binary = as.numeric(rowMeans(winning.prob.matrix)>0.5)
pred.win.prob = rowMeans(winning.prob.matrix)

sum(as.numeric(obs.win == pred.win.binary))/number.matches ## accuracy
round(mean((pred.win.prob - obs.win)**2),5) ## mean rps
round(sd((pred.win.prob - obs.win)**2),5) ## sd rps 
#rps(obs.win, pred.win, 2)
nslcpo = -sum(log(na.omit(basketball.inla$cpo$cpo)))
cat("nsdlcpo: ", nslcpo, "\n")
#summary(basketball.inla)
print(Sys.time())
```

## Logistic Regression

```{r}
print(Sys.time())
#+PTS_cur_season_oppo+FG_PCT_cur_season_oppo+FT_PCT_cur_season_oppo+FG3_PCT_cur_season_oppo+AST_cur_season_oppo+REB_cur_season_oppo+WINRATE_cur_season_oppo
basketball.inla.logi = inla(y.binary~1+a+d+h+PTS_cur_season+FG_PCT_cur_season+FT_PCT_cur_season+FG3_PCT_cur_season+AST_cur_season+REB_cur_season+WINRATE_cur_season+ PTS_LOST_cur_season+f(season,model = "ar",order = 3), data = data, family = "binomial",Ntrials = 1,control.compute=list(config = TRUE,dic=TRUE,cpo=TRUE),control.predictor = list(compute = TRUE),num.threads = 2)
#summary(basketball.inla.logi)
samp.r.logi <- inla.posterior.sample(1000, basketball.inla.logi)

## n*1000 table
predictors.r.logi=inla.posterior.sample.eval(function(...) {Predictor}, samp.r.logi)
## convert to probabilty n*1000 #pi#
prob.logi = expit(predictors.r.logi[to.be.predicted,]) 
winning.prob.logi = matrix(rep(1000*number.matches),nrow = number.matches,ncol = 1000)
for(i in 1:number.matches){
  winning.prob.logi[i,] = prob.logi[i,]/ (prob.logi[i,] + prob.logi[i+number.matches,])
}

pred.win.binary.logi = as.numeric(rowMeans(winning.prob.logi)>0.5)
pred.win.prob.logi = rowMeans(winning.prob.logi)

sum(as.numeric(obs.win == pred.win.binary.logi))/number.matches ## accuracy
round(mean((pred.win.prob.logi - obs.win)**2),5) ## mean rps
round(sd((pred.win.prob.logi - obs.win)**2),5) ## sd rps 
print(length(obs.win))
print(Sys.time())
nrow(games.sub)
```

```{r}
model <- glm(vs ~ hp, data=mtcars, family=binomial)

#define new data frame that contains predictor variable
newdata <- data.frame(hp=seq(min(mtcars$hp), max(mtcars$hp),len=500))

#use fitted model to predict values of vs
newdata$vs = predict(model, newdata, type="response")

#plot logistic regression curve
plot(vs ~ hp, data=mtcars, col="steelblue")
lines(vs ~ hp, newdata, lwd=2)

plot(data$FG_PCT_cur_season, data$y.binary)
plot(data$FG3_PCT_cur_season, data$y.binary)
abline(lm(data$y.binary ~ data$FG3_PCT_cur_season))
```
